use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=css-caelum-bridge.json");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set by Cargo");
    let dest_path = Path::new(&out_dir).join("bridge_gen.rs");

    let json = fs::read_to_string("css-caelum-bridge.json")
        .expect("Failed to read css-caelum-bridge.json");
    let bridge: serde_json::Value = serde_json::from_str(&json)
        .expect("css-caelum-bridge.json is not valid JSON");

    let mut output = String::new();
    output.push_str("// Generated by build.rs — do not edit\n");
    output.push_str("use crate::engine::{stratus, caelum};\n\n");

    for (prop_name, prop) in bridge.as_object().expect("bridge JSON must be an object") {
        let stratus_enum = prop["stratus_enum"].as_str().expect("stratus_enum missing");
        let caelum_enum = prop["caelum_enum"].as_str().expect("caelum_enum missing");
        let maps = prop["mappings"].as_array().expect("mappings missing or not an array");

        // --- Stratus→Caelum bridge ---
        output.push_str(&format!(
            "#[allow(dead_code)]\npub fn bridge_{}(v: &stratus::{}) -> caelum::{} {{\n    match v {{\n",
            prop_name, stratus_enum, caelum_enum
        ));
        for m in maps {
            let sv = m["stratus"].as_str().expect("stratus mapping missing");
            let cv = m["caelum"].as_str().expect("caelum mapping missing");
            output.push_str(&format!(
                "        stratus::{}::{} => caelum::{}::{},\n",
                stratus_enum, sv, caelum_enum, cv
            ));
        }
        output.push_str("    }\n}\n\n");

        // --- Stratus→String conversion ---
        output.push_str(&format!(
            "#[allow(dead_code)]\npub fn {}_to_string(v: &stratus::{}) -> &'static str {{\n    match v {{\n",
            prop_name, stratus_enum
        ));
        for m in maps {
            let sv = m["stratus"].as_str().expect("stratus mapping missing");
            let st = m["string"].as_str().expect("string mapping missing");
            output.push_str(&format!(
                "        stratus::{}::{} => {:?},\n",
                stratus_enum, sv, st
            ));
        }
        output.push_str("    }\n}\n\n");

        // --- String→Caelum conversion ---
        let default_caelum = prop["default"].as_str().expect("default value missing");
        output.push_str(&format!(
            "#[allow(dead_code)]\npub fn str_{}_to_caelum(s: &str) -> caelum::{} {{\n    match s {{\n",
            prop_name, caelum_enum
        ));
        for m in maps {
            let st = m["string"].as_str().expect("string mapping missing");
            let cv = m["caelum"].as_str().expect("caelum mapping missing");
            output.push_str(&format!(
                "        {:?} => caelum::{}::{},\n",
                st, caelum_enum, cv
            ));
        }
        output.push_str(&format!(
            "        _ => caelum::{}::{},\n", caelum_enum, default_caelum
        ));
        output.push_str("    }\n}\n\n");
    }

    fs::write(&dest_path, &output).expect("Failed to write bridge_gen.rs");
}
