use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=tokenizer-states.json");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set by Cargo");
    let dest_path = Path::new(&out_dir).join("state_dispatch.rs");

    let json = fs::read_to_string("tokenizer-states.json")
        .expect("Failed to read tokenizer-states.json");
    let data: serde_json::Value = serde_json::from_str(&json)
        .expect("tokenizer-states.json is not valid JSON");

    let mut output = String::new();
    output.push_str("// Generated by build.rs — do not edit\n");
    output.push_str("match self.state.clone() {\n");

    for entry in data["states"].as_array().expect("states missing or not an array") {
        let state = entry["state"].as_str().expect("state name missing");
        let handler = entry["handler"].as_str().expect("handler name missing");
        output.push_str(&format!(
            "    State::{} => self.{}(),\n",
            state, handler
        ));
    }

    output.push_str("}\n");
    fs::write(&dest_path, &output).expect("Failed to write state_dispatch.rs");
}
